In [2]:
from ethnicolr import census_ln, pred_census_ln

Using TensorFlow backend.

In [14]:
import pandas as pd

data = pd.read_csv('People_Covered_in_the_News/people_2014.csv')

In [15]:
data

,Unnamed: 0,last_name,article,article_id,race,api,black,hispanic,white
0,0,Schilling,Only a small group of reporters were admitted ...,2014_1038,white,0.005101,0.005001,0.010011,0.769949
1,1,Saun,Van Saun said the decision will ultimately be ...,2014_1332,white,0.100937,0.052501,0.059094,0.396487
2,2,Menino,I would like to extend my condolences to Mayor...,2014_1057,hispanic,0.047059,0.005033,0.422734,0.221542
3,3,Leskanic,Curtis Leskanic the goofy reliever who had ce...,2014_1038,white,0.005781,0.010136,0.010866,0.732986
4,4,la,Ramirez delivered by hitting a league best 43 ...,2014_1038,api,0.974938,0.000622,0.006068,0.015598
...,...,...,...,...,...,...,...,...,...
37064,3431,Flynn,Flynn added that “the day I left City Hall to ...,2014_1058,white,0.004116,0.033679,0.018687,0.936024
37065,3432,Mac,I was Mac in ‘Mac and Rosie ’ u2009” says Jimm...,2014_1024,api,0.575885,0.083766,0.053453,0.364894
37066,3433,Obama,In a statement Thursday President Obama said ...,2014_1058,api,0.243329,0.032075,0.169086,0.134440
37067,3434,Menino,By then my dad was a foreman ” Mr Menino wrot...,2014_1063,hispanic,0.047059,0.005033,0.422734,0.221542
37068,3435,McCarthys,The McCarthys” was picked up by CBS n nThere,2014_1024,white,0.005250,0.043070,0.018002,0.969865

In [16]:
data = data.drop(['Unnamed: 0', 'article', 'article_id', 'race', 'api', 'black', 'hispanic', 'white'], axis=1)
print(data.head())
print()
pred_census_ln(data, 'last_name', 2010)

   last_name
0  Schilling
1       Saun
2     Menino
3   Leskanic
4         la

       last_name      race       api     black  hispanic     white
0      Schilling     white  0.005101  0.005001  0.010011  0.769949
1           Saun     white  0.100937  0.052501  0.059094  0.396487
2         Menino  hispanic  0.047059  0.005033  0.422734  0.221542
3       Leskanic     white  0.005781  0.010136  0.010866  0.732986
4             la       api  0.974938  0.000622  0.006068  0.015598
...          ...       ...       ...       ...       ...       ...
37064      Flynn     white  0.004116  0.033678  0.018687  0.936024
37065        Mac       api  0.575885  0.083766  0.053453  0.364894
37066      Obama       api  0.243329  0.032075  0.169086  0.134440
37067     Menino  hispanic  0.047059  0.005033  0.422734  0.221542
37068  McCarthys     white  0.005250  0.043070  0.018002  0.969866

[37069 rows x 6 columns]